name: Build and Push to ACR

on:
  push:
    branches:
      - 'main'  # This workflow will trigger on push to the 'main' branch.

jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest  # Runs the job on the latest Ubuntu runner.

    defaults:
      run:
        shell: bash  # Use bash for commands.

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Check out the repository code.

      - name: Docker Login
        uses: azure/docker-login@v1  # Log in to Azure Container Registry.
        with:
          login-server: ${{ secrets.AZURE_URL }}  # ACR login server URL.
          username: ${{ secrets.ACR_USERNAME }}  # ACR username (service principal or admin username).
          password: ${{ secrets.ACR_PASSWORD }}  # ACR password (service principal secret).

      - name: Build and Push to ACR
        uses: docker/build-push-action@v2  # Build and push the Docker image to ACR.
        with:
          push: true  # Push the image to ACR after building.
          tags: ${{ secrets.AZURE_URL }}/pyimg-${{ github.repository | toLowerCase }}:${{ github.sha }}  # Add 'pyimg-' before repo name and use commit SHA as tag.
          file: Dockerfile  # Path to the Dockerfile in the repository.
